Second training
sugarsugar12/training_curriculum_rails7 pull request #9
Opened 2023-11-22 10:56 UTC by sugarsugar12

2023-11-22 11:04 UTC, maimai0401 reviewed
お忙しい中issue4-6のチャレンジありがとうございました。

**動画提出について**
カリキュラムにもありますとおり、アプリが動くかの確認も必要となりますので、挙動確認の動画の提出もお願いいたします。

```ruby
予定を入力し「保存」ボタンを押すとデータが保存され、日付のボックスに表示される。
※1動画で撮影が難しい場合は複数に分けて頂いても問題ございません。
※時間短縮のため予定の文字を入力した状態で撮影を開始して頂いても問題ございません。
```

お手数をおかけしますが、正確なレビューのためご協力いただければ幸いです。
その後、`再度レビュー依頼フォーム(googleフォーム)にてご提出`をお願いいたします。

```ruby
参考カリキュラム
フェーズ：発展
タイトル：アプリケーションの課題解決〜バグ修正や仕様変更をしよう〜
```

**操作についてご不明点がございましたらコネクトやチャットメンターにご相談ください。**
どうぞよろしくお願いいたします。

2023-11-22 12:45 UTC, sugarsugar12 commented
https://gyazo.com/81a7057b645ee938c28801e55fcf33b4
動作確認用の動画を添付いたします、よろしくお願いいたします。

2023-11-22 12:54 UTC, sugarsugar12 commented
https://gyazo.com/9191dd2a3f503399f15f66b3bb319013
動作確認用の動画を添付いたします、よろしくお願いいたします。

2023-11-22 13:02 UTC, sugarsugar12 commented
https://gyazo.com/ca4d44998488f326fdeeb4a26e273d98
動作確認用の動画を添付いたします、よろしくお願いいたします。

2023-11-23 05:00 UTC, maimai0401 requested changes
レビュー依頼ありがとうございます。プルリクエスト確認させていただきました。

修正点をコメントさせて頂きましたので、ご確認をお願い致します。

【次回プルリクエスト提出する際の注意点】
```ruby
①修正が終わりましたら、`コミットとプッシュ`をして、`プルリクエストに修正内容が反映されているか確認`しましょう。
②既に頂いている挙動確認の画像や動画が修正範囲だった場合、最新の画像や動画の提出をお願い致します。
③googleフォームの送信をお願いいたします。
```


ご不明点や疑問点ございましたら、チャット・コネクトメンターにご相談ください！
どうぞよろしくおねがいします。

2023-11-23 06:01 UTC, merged